name: Vue.js CI build workflow

on:
  push:
    branches:
      - deploy/vuejs
  pull_request:
    branches:
      - deploy/vuejs

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: studx-development
  GCE_INSTANCE_ZONE: asia-southeast1-b
  CI: true

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.GCE_SA_EMAIL }}
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Build the Docker image
    - name: Build
      run: |
        cd vuejs
        docker build --tag "asia.gcr.io/$PROJECT_ID/$GCE_INSTANCE-${{ secrets.APP_NAME }}-image:$GITHUB_SHA" .
  
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "asia.gcr.io/$PROJECT_ID/$GCE_INSTANCE-${{ secrets.APP_NAME }}-image:$GITHUB_SHA"

    - name: Deploy
      run: |-
        gcloud compute ssh --project $PROJECT_ID --zone $GCE_INSTANCE_ZONE sa-github-actions@$GCE_INSTANCE

      # gcloud compute instances update-container "$GCE_INSTANCE" \
        #   --zone "$GCE_INSTANCE_ZONE" \
        #   --container-image "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA"
