name: Vue.js CI build workflow

on:
  push:
    branches:
      - deploy/vuejs
  pull_request:
    branches:
      - deploy/vuejs

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: studx-development
  GCE_INSTANCE_ZONE: asia-southeast1-b
  APP_NAME: vuejs-webapp-cicd-sample
  CI: true

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.GCE_SA_EMAIL }}
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Build the Docker image
    - name: Build
      run: |
        cd vuejs
        docker build --tag "asia.gcr.io/$PROJECT_ID/$GCE_INSTANCE-$APP_NAME-image:$GITHUB_SHA" .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "asia.gcr.io/$PROJECT_ID/$GCE_INSTANCE-$APP_NAME-image:$GITHUB_SHA"

    - name: Deploy
      run: |-
        gcloud compute ssh \
          --project $PROJECT_ID \
          --zone $GCE_INSTANCE_ZONE \
          sa-github-actions@$GCE_INSTANCE \
          --command ' \
          sudo docker stop ${{ env.APP_NAME }}; \
          sudo docker rm ${{ env.APP_NAME }}; \
          sudo docker run -it -d -p 8080:8080 \
            --name ${{ env.APP_NAME }} gcr.io/studx-dev/studx-development-image@sha256:4f9144794aa2543c748d0fe45aaa92c83931662a077c7ee5b0f8aca4dc8fe976'

      # gcloud compute instances update-container "$GCE_INSTANCE" \
        #   --zone "$GCE_INSTANCE_ZONE" \
        #   --container-image "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA"
